import { Role } from '@prisma/client';
import { Permission } from './permissions.enum';

const P = Permission;

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: Object.values(P),
  CUSTOMER: [P.ADDRESS_READ, P.ADDRESS_WRITE, P.WALLET_READ, P.WALLET_TOPUP],
  COURIER: [P.ADDRESS_READ, P.WALLET_READ],
  MERCHANT: [P.ADDRESS_READ, P.ADDRESS_WRITE, P.WALLET_READ, P.TRANSACTION_READ],
  RESTAURANT: [P.ADDRESS_READ, P.ADDRESS_WRITE, P.WALLET_READ, P.TRANSACTION_READ],
  MARKET_OPERATOR: [P.ADDRESS_READ, P.ADDRESS_WRITE, P.WALLET_READ, P.TRANSACTION_READ],
  COFFEE_BRANCH: [P.ADDRESS_READ, P.WALLET_READ, P.TRANSACTION_READ],
  DICLEFUL_OPERATOR: [P.USER_READ, P.ADDRESS_READ, P.WALLET_READ, P.TRANSACTION_READ],
  DICLEFUL_DRIVER: [P.ADDRESS_READ, P.WALLET_READ],
  LOAD_CUSTOMER: [P.ADDRESS_READ, P.ADDRESS_WRITE, P.WALLET_READ, P.TRANSACTION_READ],
  CARRIER: [P.ADDRESS_READ, P.WALLET_READ, P.TRANSACTION_READ],
};

export function permissionsForRoles(roles: Role[]): Set<Permission> {
  const set = new Set<Permission>();
  for (const r of roles) (ROLE_PERMISSIONS[r] ?? []).forEach((p) => set.add(p));
  return set;
}
