import { Role } from '@prisma/client';
import { Permission } from './permissions.enum';

const P = Permission;

const MERCHANT_LIKE = [
  P.ADDRESS_READ, P.ADDRESS_WRITE, P.WALLET_READ, P.TRANSACTION_READ,
  P.STORE_READ, P.STORE_WRITE, P.PRODUCT_READ, P.PRODUCT_WRITE,
  P.CATEGORY_WRITE, P.ORDER_READ, P.ORDER_MANAGE,
];

const ADMIN_OPERATIONAL = [
  P.USER_READ, P.ADDRESS_READ, P.STORE_READ, P.STORE_WRITE, P.STORE_MANAGE_ALL,
  P.PRODUCT_READ, P.PRODUCT_WRITE, P.CATEGORY_WRITE,
  P.ORDER_READ, P.ORDER_MANAGE, P.DELIVERY_READ, P.DELIVERY_MANAGE, P.AUDIT_READ,
];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: Object.values(P),
  ADMIN: ADMIN_OPERATIONAL,
  CUSTOMER: [P.ADDRESS_READ, P.ADDRESS_WRITE, P.WALLET_READ, P.WALLET_TOPUP, P.STORE_READ, P.PRODUCT_READ, P.ORDER_READ, P.ORDER_WRITE],
  COURIER: [P.ADDRESS_READ, P.WALLET_READ, P.TRANSACTION_READ, P.DELIVERY_READ, P.DELIVERY_CLAIM, P.DELIVERY_MANAGE],
  MERCHANT: MERCHANT_LIKE,
  RESTAURANT: MERCHANT_LIKE,
  MARKET_OPERATOR: MERCHANT_LIKE,
  COFFEE_BRANCH: [P.ADDRESS_READ, P.WALLET_READ, P.TRANSACTION_READ, P.STORE_READ, P.PRODUCT_READ, P.PRODUCT_WRITE, P.ORDER_READ, P.ORDER_MANAGE],
  DICLEFUL_OPERATOR: [P.USER_READ, P.ADDRESS_READ, P.WALLET_READ, P.TRANSACTION_READ],
  DICLEFUL_DRIVER: [P.ADDRESS_READ, P.WALLET_READ],
  LOAD_CUSTOMER: [P.ADDRESS_READ, P.ADDRESS_WRITE, P.WALLET_READ, P.TRANSACTION_READ],
  CARRIER: [P.ADDRESS_READ, P.WALLET_READ, P.TRANSACTION_READ],
};

export function permissionsForRoles(roles: Role[]): Set<Permission> {
  const set = new Set<Permission>();
  for (const r of roles) (ROLE_PERMISSIONS[r] ?? []).forEach((p) => set.add(p));
  return set;
}